FROM ubuntu:22.04

# Install dependencies and default Python from apt
RUN apt update && apt install -y     python3 python3-venv python3-pip     mc     wireguard     iproute2     iputils-ping     openresolv     && ln -sf /usr/bin/python3 /usr/bin/python     && ln -sf /usr/local/bin/openai /usr/bin/openai

# Install openai
RUN python3 -m pip install --upgrade pip     && python3 -m pip install openai

COPY wg0.conf /etc/wireguard/wg0.conf

CMD ["bash", "-c", "wg-quick up wg0 && bash"]
