#!/bin/bash

#wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
#chmod +x appimagetool-x86_64.appimage-scripts

# Start build-scripts
sudo ARCH=x86_64 ./appimagetool-x86_64.AppImage viewer.AppDir/
sudo chmod a+x viewer-x86_64.AppImage

# Launch appimage-scripts
./viewer-x86_64.AppImage

